format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/um7-git.2024.07.03_access-esm1.5-kgxooyp2s476dd4zc5mgtwhxfknkhnoe/bin/um_hg3.exe
  hashes:
    binhash: 3180dda616c7dfe63d8134e00bff2641
    md5: 1b7874ffb5e34ec50b6a68abbb7769a6
work/ice/cice_access_360x300_12x1_12p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/cice4-git.2024.05.21_access-esm1.5-hhtnigwxdyz7ta4dv3gvhwulze6hxqra/bin/cice_access_360x300_12x1_12p.exe
  hashes:
    binhash: 818f213e53d30fc307b565c35939382c
    md5: 04fd88249ebc16e3f560fc265838e9d1
work/ocean/fms_ACCESS-CM.x:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/mom5-git.access-esm1.5_2024.06.20_access-esm1.5-wxxrc3ivrjz76yx565ddkuuiwoqpalko/bin/fms_ACCESS-CM.x
  hashes:
    binhash: a7a3151fb1b814f9e94f05e637b86a44
    md5: 241db68e6164fac77c59da99ffb1d3b1
